.TH XCLICK 1 "Date: 2012/01/05 14:55:00" "XCLICK"
.SH NAME
xclick \- trigger mouse click in X after mouse has stopped moving.
.SH SYNOPSIS
.TP
\fBxclick\fP
.SH OVERVIEW
When run without any argument, \fBxclick\fP monitors your mouse movement.  When
the mouse stops moving it triggers a left mouse click.

.SH BUGS
They're there in hiding.

.SH CAVEAT
xclick depends on the xdotool program to do the actual clicking because I'm too
lazy to do it the proper way at the moment.

.SH SEE-ALSO
xdotool(1)

.SH COPYRIGHT
\fBCopyright (C) 2012 Nazri Ramliy.
